# Generated by Django 5.2.4 on 2025-09-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('beer_servings', models.IntegerField()),
                ('spirit_servings', models.IntegerField()),
                ('wine_servings', models.IntegerField()),
                ('total_litres_of_pure_alcohol', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='LifeExpectancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GhoCode', models.CharField(max_length=50)),
                ('GhoDisplay', models.CharField(max_length=100)),
                ('PublishStateCode', models.CharField(max_length=50)),
                ('PublishStateDisplay', models.CharField(max_length=100)),
                ('YearCode', models.CharField(max_length=10)),
                ('YearDisplay', models.CharField(max_length=10)),
                ('RegionCode', models.CharField(max_length=50)),
                ('RegionDisplay', models.CharField(max_length=100)),
                ('WorldBankIncomeGroupGroupCode', models.CharField(max_length=50)),
                ('WorldBankIncomeGroupDisplay', models.CharField(max_length=100)),
                ('CountryCode', models.CharField(max_length=10)),
                ('CountryDisplay', models.CharField(max_length=100)),
                ('SexCode', models.CharField(max_length=10)),
                ('SexDisplay', models.CharField(max_length=20)),
                ('DisplayValue', models.CharField(max_length=20)),
                ('Numeric', models.FloatField()),
            ],
        ),
    ]
