# Generated by Django 5.2.4 on 2025-09-25 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alcohol_life', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lifeexpectancy',
            old_name='CountryCode',
            new_name='country_code',
        ),
        migrations.RenameField(
            model_name='lifeexpectancy',
            old_name='CountryDisplay',
            new_name='country_display',
        ),
        migrations.RenameField(
            model_name='lifeexpectancy',
            old_name='DisplayValue',
            new_name='display_value',
        ),
        migrations.RenameField(
            model_name='lifeexpectancy',
            old_name='GhoCode',
            new_name='gho_code',
        ),
        migrations.RenameField(
            model_name='lifeexpectancy',
            old_name='GhoDisplay',
            new_name='gho_display',
        ),
        migrations.RenameField(
            model_name='lifeexpectancy',
            old_name='Numeric',
            new_name='numeric',
        ),
        migrations.RenameField(
            model_name='lifeexpectancy',
            old_name='PublishStateCode',
            new_name='publish_state_code',
        ),
        migrations.RenameField(
            model_name='lifeexpectancy',
            old_name='PublishStateDisplay',
            new_name='publish_state_display',
        ),
        migrations.RenameField(
            model_name='lifeexpectancy',
            old_name='RegionCode',
            new_name='region_code',
        ),
        migrations.RenameField(
            model_name='lifeexpectancy',
            old_name='RegionDisplay',
            new_name='region_display',
        ),
        migrations.RenameField(
            model_name='lifeexpectancy',
            old_name='SexCode',
            new_name='sex_code',
        ),
        migrations.RenameField(
            model_name='lifeexpectancy',
            old_name='SexDisplay',
            new_name='sex_display',
        ),
        migrations.RenameField(
            model_name='lifeexpectancy',
            old_name='WorldBankIncomeGroupDisplay',
            new_name='world_bank_income_group_display',
        ),
        migrations.RenameField(
            model_name='lifeexpectancy',
            old_name='WorldBankIncomeGroupGroupCode',
            new_name='world_bank_income_group_group_code',
        ),
        migrations.RenameField(
            model_name='lifeexpectancy',
            old_name='YearCode',
            new_name='year_code',
        ),
        migrations.RenameField(
            model_name='lifeexpectancy',
            old_name='YearDisplay',
            new_name='year_display',
        ),
    ]
