import dotenv from 'dotenv';

dotenv.config();

export const {
  PORT,
  NODE_ENV,
  ORIGIN_URLS,
  NEXT_PUBLIC_DJANGO_URL,
  SPOTIFY_CLIENT_ID,
  SPOTIFY_CLIENT_SECRET,
  JWT_SECRET_KEY,
  TOKEN_HEADER_KEY,
  RESEND_KEY,
  EMAIL_RECEIVER,
  DATABASE_URL,
  DATABASE_PUBLIC_URL,
} = process.env;
