name: Frontend CI/CD Pipeline

on:
  push:
    branches: [ main ]
    paths: 
      - 'portfolio-project/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'portfolio-project/**'

jobs:
  test-and-build:
    name: Test and Build Frontend
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./portfolio-project
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './portfolio-project/package-lock.json'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Execute tests
        run: npm test
      
      - name: Build application
        run: npm run build
      
      - name: Verify build artifacts
        run: |
          if [ -d ".next" ]; then
            echo "Build completed successfully - output directory verified"
          else
            echo "Build failed - output directory not found"
            exit 1
          fi
